name: Build and Release

on:
  push:
    tags:
      - "v*" # This triggers on version tags
  pull_request:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Step to build Raylib (if it's not pre-built)
      - name: Build Raylib
        run: |
          cd lib/raylib
          mkdir build && cd build
          cmake ..
          make

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: build
        run: ctest -C ${{ env.BUILD_TYPE }}

      - name: Create Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p release
          cp build/my_program release/
          cd release
          zip release.zip my_program
        # Add steps to upload the zip as a release artifact if needed
